version: "2"
linters:
  default: standard
  enable:
    - lll
  disable:
    - unused # gopls handles this faster
  settings:
    lll:
      line-length: 120
    govet:
      # Disable checks gopls already handles
      disable:
        - printf # gopls does this
        - assign # gopls does this
